version: "3"

services:
  react:
    build:
      context: ./packages/react
    volumes:
      - ./packages/react:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    ports:
      - "3000:3000"
  express:
    build:
      context: ./packages/express
    volumes:
      - ./packages/express:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    ports:
      - "3001:3001"
    links:
      - mysql:mysql
  mysql:
    image: mysql:5.7
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: marchmadness
      MYSQL_USER: admin
      MYSQL_PASSWORD: r@nd0m
    restart: unless-stopped
    ports:
      - "3306:3306"

volumes:
  mysql:
